name: tdd-test CI

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: npm install
        
      - name: Run tests
        uses: npm run test